# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hades_D.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(838, 467)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.tabWidget_hades = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget_hades.setStatusTip(_fromUtf8(""))
        self.tabWidget_hades.setObjectName(_fromUtf8("tabWidget_hades"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_importar_ruta = QtGui.QPushButton(self.tab)
        self.pushButton_importar_ruta.setObjectName(_fromUtf8("pushButton_importar_ruta"))
        self.horizontalLayout.addWidget(self.pushButton_importar_ruta)
        self.lineEdit_ruta = QtGui.QLineEdit(self.tab)
        self.lineEdit_ruta.setObjectName(_fromUtf8("lineEdit_ruta"))
        self.horizontalLayout.addWidget(self.lineEdit_ruta)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_archivos_ruta = QtGui.QLabel(self.tab)
        self.label_archivos_ruta.setObjectName(_fromUtf8("label_archivos_ruta"))
        self.verticalLayout.addWidget(self.label_archivos_ruta)
        self.listWidget_archivos_ruta = QtGui.QListWidget(self.tab)
        self.listWidget_archivos_ruta.setObjectName(_fromUtf8("listWidget_archivos_ruta"))
        self.verticalLayout.addWidget(self.listWidget_archivos_ruta)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_selecciona_csv = QtGui.QPushButton(self.tab)
        self.pushButton_selecciona_csv.setObjectName(_fromUtf8("pushButton_selecciona_csv"))
        self.verticalLayout_3.addWidget(self.pushButton_selecciona_csv)
        self.pushButton_selecciona_todos_csv = QtGui.QPushButton(self.tab)
        self.pushButton_selecciona_todos_csv.setObjectName(_fromUtf8("pushButton_selecciona_todos_csv"))
        self.verticalLayout_3.addWidget(self.pushButton_selecciona_todos_csv)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton_deselecciona_csv = QtGui.QPushButton(self.tab)
        self.pushButton_deselecciona_csv.setObjectName(_fromUtf8("pushButton_deselecciona_csv"))
        self.verticalLayout_3.addWidget(self.pushButton_deselecciona_csv)
        self.pushButton_deselecciona_todos_csv = QtGui.QPushButton(self.tab)
        self.pushButton_deselecciona_todos_csv.setObjectName(_fromUtf8("pushButton_deselecciona_todos_csv"))
        self.verticalLayout_3.addWidget(self.pushButton_deselecciona_todos_csv)
        spacerItem2 = QtGui.QSpacerItem(20, 48, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_archivos_seleccion = QtGui.QLabel(self.tab)
        self.label_archivos_seleccion.setObjectName(_fromUtf8("label_archivos_seleccion"))
        self.verticalLayout_2.addWidget(self.label_archivos_seleccion)
        self.listWidget_archivos_implantacion = QtGui.QListWidget(self.tab)
        self.listWidget_archivos_implantacion.setObjectName(_fromUtf8("listWidget_archivos_implantacion"))
        self.verticalLayout_2.addWidget(self.listWidget_archivos_implantacion)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget_hades.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_nuevo_grupo = QtGui.QLabel(self.tab_2)
        self.label_nuevo_grupo.setObjectName(_fromUtf8("label_nuevo_grupo"))
        self.verticalLayout_6.addWidget(self.label_nuevo_grupo)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lineEdit_nuevo_grupo = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_nuevo_grupo.setObjectName(_fromUtf8("lineEdit_nuevo_grupo"))
        self.horizontalLayout_3.addWidget(self.lineEdit_nuevo_grupo)
        self.pushButton_crear_nuevo_grupo = QtGui.QPushButton(self.tab_2)
        self.pushButton_crear_nuevo_grupo.setObjectName(_fromUtf8("pushButton_crear_nuevo_grupo"))
        self.horizontalLayout_3.addWidget(self.pushButton_crear_nuevo_grupo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_casos_carga = QtGui.QLabel(self.tab_2)
        self.label_casos_carga.setObjectName(_fromUtf8("label_casos_carga"))
        self.verticalLayout_4.addWidget(self.label_casos_carga)
        self.listWidget_casos_carga = QtGui.QListWidget(self.tab_2)
        self.listWidget_casos_carga.setObjectName(_fromUtf8("listWidget_casos_carga"))
        self.verticalLayout_4.addWidget(self.listWidget_casos_carga)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.groupBox_relacion = QtGui.QGroupBox(self.tab_2)
        self.groupBox_relacion.setObjectName(_fromUtf8("groupBox_relacion"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_relacion)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.radioButton_Y = QtGui.QRadioButton(self.groupBox_relacion)
        self.radioButton_Y.setWhatsThis(_fromUtf8(""))
        self.radioButton_Y.setChecked(True)
        self.radioButton_Y.setObjectName(_fromUtf8("radioButton_Y"))
        self.verticalLayout_9.addWidget(self.radioButton_Y)
        self.radioButton_YO = QtGui.QRadioButton(self.groupBox_relacion)
        self.radioButton_YO.setObjectName(_fromUtf8("radioButton_YO"))
        self.verticalLayout_9.addWidget(self.radioButton_YO)
        self.radioButton_O = QtGui.QRadioButton(self.groupBox_relacion)
        self.radioButton_O.setObjectName(_fromUtf8("radioButton_O"))
        self.verticalLayout_9.addWidget(self.radioButton_O)
        self.verticalLayout_13.addWidget(self.groupBox_relacion)
        spacerItem3 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem3)
        self.pushButton_selecciona_cc = QtGui.QPushButton(self.tab_2)
        self.pushButton_selecciona_cc.setObjectName(_fromUtf8("pushButton_selecciona_cc"))
        self.verticalLayout_13.addWidget(self.pushButton_selecciona_cc)
        self.pushButton_selecciona_todos_cc = QtGui.QPushButton(self.tab_2)
        self.pushButton_selecciona_todos_cc.setObjectName(_fromUtf8("pushButton_selecciona_todos_cc"))
        self.verticalLayout_13.addWidget(self.pushButton_selecciona_todos_cc)
        spacerItem4 = QtGui.QSpacerItem(20, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem4)
        self.pushButton_deselecciona_cc = QtGui.QPushButton(self.tab_2)
        self.pushButton_deselecciona_cc.setObjectName(_fromUtf8("pushButton_deselecciona_cc"))
        self.verticalLayout_13.addWidget(self.pushButton_deselecciona_cc)
        self.pushButton_deselecciona_todos_cc = QtGui.QPushButton(self.tab_2)
        self.pushButton_deselecciona_todos_cc.setObjectName(_fromUtf8("pushButton_deselecciona_todos_cc"))
        self.verticalLayout_13.addWidget(self.pushButton_deselecciona_todos_cc)
        spacerItem5 = QtGui.QSpacerItem(20, 38, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem5)
        self.gridLayout_4.addLayout(self.verticalLayout_13, 1, 1, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_casos_carga_grupo = QtGui.QLabel(self.tab_2)
        self.label_casos_carga_grupo.setObjectName(_fromUtf8("label_casos_carga_grupo"))
        self.verticalLayout_5.addWidget(self.label_casos_carga_grupo)
        self.listWidget_casos_carga_grupo = QtGui.QListWidget(self.tab_2)
        self.listWidget_casos_carga_grupo.setObjectName(_fromUtf8("listWidget_casos_carga_grupo"))
        self.verticalLayout_5.addWidget(self.listWidget_casos_carga_grupo)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 2, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem6 = QtGui.QSpacerItem(20, 158, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem6)
        self.pushButton_deselecciona_grp = QtGui.QPushButton(self.tab_2)
        self.pushButton_deselecciona_grp.setObjectName(_fromUtf8("pushButton_deselecciona_grp"))
        self.verticalLayout_10.addWidget(self.pushButton_deselecciona_grp)
        self.pushButton_deselecciona_todos_grp = QtGui.QPushButton(self.tab_2)
        self.pushButton_deselecciona_todos_grp.setObjectName(_fromUtf8("pushButton_deselecciona_todos_grp"))
        self.verticalLayout_10.addWidget(self.pushButton_deselecciona_todos_grp)
        spacerItem7 = QtGui.QSpacerItem(20, 118, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem7)
        self.gridLayout_4.addLayout(self.verticalLayout_10, 1, 3, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_grupos_casos_carga = QtGui.QLabel(self.tab_2)
        self.label_grupos_casos_carga.setObjectName(_fromUtf8("label_grupos_casos_carga"))
        self.verticalLayout_8.addWidget(self.label_grupos_casos_carga)
        self.listWidget_grupos_casos_carga = QtGui.QListWidget(self.tab_2)
        self.listWidget_grupos_casos_carga.setObjectName(_fromUtf8("listWidget_grupos_casos_carga"))
        self.verticalLayout_8.addWidget(self.listWidget_grupos_casos_carga)
        self.gridLayout_4.addLayout(self.verticalLayout_8, 1, 4, 1, 1)
        self.tabWidget_hades.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_nudos_apoyo = QtGui.QLabel(self.tab_3)
        self.label_nudos_apoyo.setObjectName(_fromUtf8("label_nudos_apoyo"))
        self.verticalLayout_7.addWidget(self.label_nudos_apoyo)
        self.listWidget_nudos_apoyo = QtGui.QListWidget(self.tab_3)
        self.listWidget_nudos_apoyo.setObjectName(_fromUtf8("listWidget_nudos_apoyo"))
        self.verticalLayout_7.addWidget(self.listWidget_nudos_apoyo)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        spacerItem8 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem8)
        self.pushButton_nudos = QtGui.QPushButton(self.tab_3)
        self.pushButton_nudos.setObjectName(_fromUtf8("pushButton_nudos"))
        self.verticalLayout_12.addWidget(self.pushButton_nudos)
        self.pushButton_deseleccionar_nudos = QtGui.QPushButton(self.tab_3)
        self.pushButton_deseleccionar_nudos.setObjectName(_fromUtf8("pushButton_deseleccionar_nudos"))
        self.verticalLayout_12.addWidget(self.pushButton_deseleccionar_nudos)
        self.label_nudos = QtGui.QLabel(self.tab_3)
        self.label_nudos.setObjectName(_fromUtf8("label_nudos"))
        self.verticalLayout_12.addWidget(self.label_nudos)
        self.lineEdit_nudos = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_nudos.setReadOnly(True)
        self.lineEdit_nudos.setObjectName(_fromUtf8("lineEdit_nudos"))
        self.verticalLayout_12.addWidget(self.lineEdit_nudos)
        self.label_apoyo = QtGui.QLabel(self.tab_3)
        self.label_apoyo.setObjectName(_fromUtf8("label_apoyo"))
        self.verticalLayout_12.addWidget(self.label_apoyo)
        self.lineEdit_apoyo = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_apoyo.setObjectName(_fromUtf8("lineEdit_apoyo"))
        self.verticalLayout_12.addWidget(self.lineEdit_apoyo)
        self.pushButton_apoyo = QtGui.QPushButton(self.tab_3)
        self.pushButton_apoyo.setObjectName(_fromUtf8("pushButton_apoyo"))
        self.verticalLayout_12.addWidget(self.pushButton_apoyo)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem9)
        self.pushButton_deselecciona_apy = QtGui.QPushButton(self.tab_3)
        self.pushButton_deselecciona_apy.setObjectName(_fromUtf8("pushButton_deselecciona_apy"))
        self.verticalLayout_12.addWidget(self.pushButton_deselecciona_apy)
        self.pushButton_deselecciona_todos_apy = QtGui.QPushButton(self.tab_3)
        self.pushButton_deselecciona_todos_apy.setObjectName(_fromUtf8("pushButton_deselecciona_todos_apy"))
        self.verticalLayout_12.addWidget(self.pushButton_deselecciona_todos_apy)
        spacerItem10 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem10)
        self.gridLayout_6.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_apoyos_implantacion = QtGui.QLabel(self.tab_3)
        self.label_apoyos_implantacion.setObjectName(_fromUtf8("label_apoyos_implantacion"))
        self.verticalLayout_11.addWidget(self.label_apoyos_implantacion)
        self.listWidget_apoyos_implantacion = QtGui.QListWidget(self.tab_3)
        self.listWidget_apoyos_implantacion.setObjectName(_fromUtf8("listWidget_apoyos_implantacion"))
        self.verticalLayout_11.addWidget(self.listWidget_apoyos_implantacion)
        self.gridLayout_6.addLayout(self.verticalLayout_11, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget_hades.addTab(self.tab_3, _fromUtf8(""))
        self.tab_7 = QtGui.QWidget()
        self.tab_7.setObjectName(_fromUtf8("tab_7"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_7)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.label_apoyos = QtGui.QLabel(self.tab_7)
        self.label_apoyos.setObjectName(_fromUtf8("label_apoyos"))
        self.verticalLayout_14.addWidget(self.label_apoyos)
        self.listWidget_apoyos = QtGui.QListWidget(self.tab_7)
        self.listWidget_apoyos.setObjectName(_fromUtf8("listWidget_apoyos"))
        self.verticalLayout_14.addWidget(self.listWidget_apoyos)
        self.gridLayout_7.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        spacerItem11 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem11)
        self.pushButton_apoyos = QtGui.QPushButton(self.tab_7)
        self.pushButton_apoyos.setObjectName(_fromUtf8("pushButton_apoyos"))
        self.verticalLayout_15.addWidget(self.pushButton_apoyos)
        self.pushButton_deseleccionar_apoyos = QtGui.QPushButton(self.tab_7)
        self.pushButton_deseleccionar_apoyos.setObjectName(_fromUtf8("pushButton_deseleccionar_apoyos"))
        self.verticalLayout_15.addWidget(self.pushButton_deseleccionar_apoyos)
        self.label_apoyos_seleccionados = QtGui.QLabel(self.tab_7)
        self.label_apoyos_seleccionados.setObjectName(_fromUtf8("label_apoyos_seleccionados"))
        self.verticalLayout_15.addWidget(self.label_apoyos_seleccionados)
        self.lineEdit_apoyos_seleccionados = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_apoyos_seleccionados.setReadOnly(True)
        self.lineEdit_apoyos_seleccionados.setObjectName(_fromUtf8("lineEdit_apoyos_seleccionados"))
        self.verticalLayout_15.addWidget(self.lineEdit_apoyos_seleccionados)
        self.label_n_puntos_apoyo = QtGui.QLabel(self.tab_7)
        self.label_n_puntos_apoyo.setObjectName(_fromUtf8("label_n_puntos_apoyo"))
        self.verticalLayout_15.addWidget(self.label_n_puntos_apoyo)
        self.lineEdit_puntos_apoyo = QtGui.QLineEdit(self.tab_7)
        self.lineEdit_puntos_apoyo.setObjectName(_fromUtf8("lineEdit_puntos_apoyo"))
        self.verticalLayout_15.addWidget(self.lineEdit_puntos_apoyo)
        self.pushButton_puntos = QtGui.QPushButton(self.tab_7)
        self.pushButton_puntos.setObjectName(_fromUtf8("pushButton_puntos"))
        self.verticalLayout_15.addWidget(self.pushButton_puntos)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem12)
        self.pushButton_deselecciona_pto = QtGui.QPushButton(self.tab_7)
        self.pushButton_deselecciona_pto.setObjectName(_fromUtf8("pushButton_deselecciona_pto"))
        self.verticalLayout_15.addWidget(self.pushButton_deselecciona_pto)
        self.pushButton_deselecciona_todos_pto = QtGui.QPushButton(self.tab_7)
        self.pushButton_deselecciona_todos_pto.setObjectName(_fromUtf8("pushButton_deselecciona_todos_pto"))
        self.verticalLayout_15.addWidget(self.pushButton_deselecciona_todos_pto)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem13)
        self.gridLayout_7.addLayout(self.verticalLayout_15, 0, 1, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_puntos_apoyo = QtGui.QLabel(self.tab_7)
        self.label_puntos_apoyo.setObjectName(_fromUtf8("label_puntos_apoyo"))
        self.verticalLayout_16.addWidget(self.label_puntos_apoyo)
        self.listWidget_puntos_apoyo = QtGui.QListWidget(self.tab_7)
        self.listWidget_puntos_apoyo.setObjectName(_fromUtf8("listWidget_puntos_apoyo"))
        self.verticalLayout_16.addWidget(self.listWidget_puntos_apoyo)
        self.gridLayout_7.addLayout(self.verticalLayout_16, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget_hades.addTab(self.tab_7, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.pushButton_reacciones_rsa = QtGui.QPushButton(self.tab_4)
        self.pushButton_reacciones_rsa.setGeometry(QtCore.QRect(650, 20, 151, 23))
        self.pushButton_reacciones_rsa.setObjectName(_fromUtf8("pushButton_reacciones_rsa"))
        self.pushButton_reacciones_implantacion = QtGui.QPushButton(self.tab_4)
        self.pushButton_reacciones_implantacion.setGeometry(QtCore.QRect(650, 50, 151, 23))
        self.pushButton_reacciones_implantacion.setObjectName(_fromUtf8("pushButton_reacciones_implantacion"))
        self.groupBox_coeficiente_implantacion = QtGui.QGroupBox(self.tab_4)
        self.groupBox_coeficiente_implantacion.setGeometry(QtCore.QRect(10, 20, 611, 271))
        self.groupBox_coeficiente_implantacion.setObjectName(_fromUtf8("groupBox_coeficiente_implantacion"))
        self.comboBox_coeficiente_implantacion = QtGui.QComboBox(self.groupBox_coeficiente_implantacion)
        self.comboBox_coeficiente_implantacion.setGeometry(QtCore.QRect(240, 50, 131, 22))
        self.comboBox_coeficiente_implantacion.setEditable(True)
        self.comboBox_coeficiente_implantacion.setObjectName(_fromUtf8("comboBox_coeficiente_implantacion"))
        self.label_coeficiente_implantacion = QtGui.QLabel(self.groupBox_coeficiente_implantacion)
        self.label_coeficiente_implantacion.setGeometry(QtCore.QRect(240, 30, 151, 16))
        self.label_coeficiente_implantacion.setObjectName(_fromUtf8("label_coeficiente_implantacion"))
        self.label_grupos_implantacion = QtGui.QLabel(self.groupBox_coeficiente_implantacion)
        self.label_grupos_implantacion.setGeometry(QtCore.QRect(20, 30, 181, 16))
        self.label_grupos_implantacion.setObjectName(_fromUtf8("label_grupos_implantacion"))
        self.listWidget_grupos_implantacion = QtGui.QListWidget(self.groupBox_coeficiente_implantacion)
        self.listWidget_grupos_implantacion.setGeometry(QtCore.QRect(20, 50, 201, 192))
        self.listWidget_grupos_implantacion.setObjectName(_fromUtf8("listWidget_grupos_implantacion"))
        self.label_coeficientes_implantacion = QtGui.QLabel(self.groupBox_coeficiente_implantacion)
        self.label_coeficientes_implantacion.setGeometry(QtCore.QRect(390, 30, 211, 16))
        self.label_coeficientes_implantacion.setObjectName(_fromUtf8("label_coeficientes_implantacion"))
        self.listWidget_coeficientes_implantacion = QtGui.QListWidget(self.groupBox_coeficiente_implantacion)
        self.listWidget_coeficientes_implantacion.setGeometry(QtCore.QRect(390, 50, 201, 192))
        self.listWidget_coeficientes_implantacion.setObjectName(_fromUtf8("listWidget_coeficientes_implantacion"))
        self.pushButton_selecciona_grp_coef = QtGui.QPushButton(self.groupBox_coeficiente_implantacion)
        self.pushButton_selecciona_grp_coef.setGeometry(QtCore.QRect(240, 100, 75, 23))
        self.pushButton_selecciona_grp_coef.setObjectName(_fromUtf8("pushButton_selecciona_grp_coef"))
        self.pushButton_selecciona_todos_grp_coef = QtGui.QPushButton(self.groupBox_coeficiente_implantacion)
        self.pushButton_selecciona_todos_grp_coef.setGeometry(QtCore.QRect(240, 130, 75, 23))
        self.pushButton_selecciona_todos_grp_coef.setObjectName(_fromUtf8("pushButton_selecciona_todos_grp_coef"))
        self.pushButton_deselecciona_grp_coef = QtGui.QPushButton(self.groupBox_coeficiente_implantacion)
        self.pushButton_deselecciona_grp_coef.setGeometry(QtCore.QRect(240, 190, 75, 23))
        self.pushButton_deselecciona_grp_coef.setToolTip(_fromUtf8(""))
        self.pushButton_deselecciona_grp_coef.setObjectName(_fromUtf8("pushButton_deselecciona_grp_coef"))
        self.pushButton_deselecciona_todos_grp_coef = QtGui.QPushButton(self.groupBox_coeficiente_implantacion)
        self.pushButton_deselecciona_todos_grp_coef.setGeometry(QtCore.QRect(240, 220, 75, 23))
        self.pushButton_deselecciona_todos_grp_coef.setObjectName(_fromUtf8("pushButton_deselecciona_todos_grp_coef"))
        self.pushButton_cuadro_implantacion = QtGui.QPushButton(self.tab_4)
        self.pushButton_cuadro_implantacion.setGeometry(QtCore.QRect(650, 80, 151, 23))
        self.pushButton_cuadro_implantacion.setObjectName(_fromUtf8("pushButton_cuadro_implantacion"))
        self.tabWidget_hades.addTab(self.tab_4, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget_hades.addTab(self.tab_6, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tabWidget_hades.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_5.addWidget(self.tabWidget_hades, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuProyecto = QtGui.QMenu(self.menubar)
        self.menuProyecto.setObjectName(_fromUtf8("menuProyecto"))
        self.menuImplantaci_n = QtGui.QMenu(self.menubar)
        self.menuImplantaci_n.setObjectName(_fromUtf8("menuImplantaci_n"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionDatos_de_proyecto = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../iconos/Programming Edit Property.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatos_de_proyecto.setIcon(icon)
        self.actionDatos_de_proyecto.setObjectName(_fromUtf8("actionDatos_de_proyecto"))
        self.actionPropiedades = QtGui.QAction(MainWindow)
        self.actionPropiedades.setObjectName(_fromUtf8("actionPropiedades"))
        self.menuProyecto.addAction(self.actionDatos_de_proyecto)
        self.menuImplantaci_n.addAction(self.actionPropiedades)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuProyecto.menuAction())
        self.menubar.addAction(self.menuImplantaci_n.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_hades.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_importar_ruta, self.lineEdit_ruta)
        MainWindow.setTabOrder(self.lineEdit_ruta, self.listWidget_archivos_ruta)
        MainWindow.setTabOrder(self.listWidget_archivos_ruta, self.pushButton_selecciona_csv)
        MainWindow.setTabOrder(self.pushButton_selecciona_csv, self.pushButton_selecciona_todos_csv)
        MainWindow.setTabOrder(self.pushButton_selecciona_todos_csv, self.listWidget_archivos_implantacion)
        MainWindow.setTabOrder(self.listWidget_archivos_implantacion, self.pushButton_deselecciona_csv)
        MainWindow.setTabOrder(self.pushButton_deselecciona_csv, self.pushButton_deselecciona_todos_csv)
        MainWindow.setTabOrder(self.pushButton_deselecciona_todos_csv, self.lineEdit_nuevo_grupo)
        MainWindow.setTabOrder(self.lineEdit_nuevo_grupo, self.pushButton_crear_nuevo_grupo)
        MainWindow.setTabOrder(self.pushButton_crear_nuevo_grupo, self.listWidget_casos_carga)
        MainWindow.setTabOrder(self.listWidget_casos_carga, self.pushButton_selecciona_todos_cc)
        MainWindow.setTabOrder(self.pushButton_selecciona_todos_cc, self.pushButton_selecciona_cc)
        MainWindow.setTabOrder(self.pushButton_selecciona_cc, self.listWidget_casos_carga_grupo)
        MainWindow.setTabOrder(self.listWidget_casos_carga_grupo, self.listWidget_nudos_apoyo)
        MainWindow.setTabOrder(self.listWidget_nudos_apoyo, self.lineEdit_nudos)
        MainWindow.setTabOrder(self.lineEdit_nudos, self.lineEdit_apoyo)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Hades beta", None))
        self.pushButton_importar_ruta.setStatusTip(_translate("MainWindow", "Busca la ruta donde se encuentran los archivos csv con las reacciones de Robot.", None))
        self.pushButton_importar_ruta.setText(_translate("MainWindow", "Importar ruta donde se encuentran los archivos csv con las reacciones:", None))
        self.lineEdit_ruta.setStatusTip(_translate("MainWindow", "Ruta donde se encuentran los archivos csv con las reacciones de Robot.", None))
        self.label_archivos_ruta.setText(_translate("MainWindow", "Lista de archivos csv en ruta:", None))
        self.listWidget_archivos_ruta.setStatusTip(_translate("MainWindow", "Lista de archivos csv en ruta seleccionada.", None))
        self.pushButton_selecciona_csv.setStatusTip(_translate("MainWindow", "Selecciona los archivos de csv para las implantaciones.", None))
        self.pushButton_selecciona_csv.setText(_translate("MainWindow", ">", None))
        self.pushButton_selecciona_todos_csv.setStatusTip(_translate("MainWindow", "Selecciona todos los archivos de csv para las implantaciones", None))
        self.pushButton_selecciona_todos_csv.setText(_translate("MainWindow", ">>", None))
        self.pushButton_deselecciona_csv.setStatusTip(_translate("MainWindow", "Elimina de la selección los archivos de csv para las implantaciones", None))
        self.pushButton_deselecciona_csv.setText(_translate("MainWindow", "<", None))
        self.pushButton_deselecciona_todos_csv.setStatusTip(_translate("MainWindow", "Elimina de la selección todos los archivos de csv para las implantaciones", None))
        self.pushButton_deselecciona_todos_csv.setText(_translate("MainWindow", "<<", None))
        self.label_archivos_seleccion.setText(_translate("MainWindow", "Lista de archivos csv para implantaciones:", None))
        self.listWidget_archivos_implantacion.setStatusTip(_translate("MainWindow", "Lista de archivos csv seleccionados para implantaciones.", None))
        self.tabWidget_hades.setTabText(self.tabWidget_hades.indexOf(self.tab), _translate("MainWindow", "Archivos csv", None))
        self.label_nuevo_grupo.setText(_translate("MainWindow", "Nuevo grupo de casos de carga:", None))
        self.lineEdit_nuevo_grupo.setStatusTip(_translate("MainWindow", "Nuevo grupo de casos de carga.", None))
        self.pushButton_crear_nuevo_grupo.setStatusTip(_translate("MainWindow", "Crea un nuevo grupo de casos de carga.", None))
        self.pushButton_crear_nuevo_grupo.setText(_translate("MainWindow", "Crear", None))
        self.label_casos_carga.setText(_translate("MainWindow", "Casos de carga en archivos csv:", None))
        self.listWidget_casos_carga.setStatusTip(_translate("MainWindow", "Lista con los casos de carga en los modelos de Robot.", None))
        self.groupBox_relacion.setTitle(_translate("MainWindow", "Relación:", None))
        self.radioButton_Y.setToolTip(_translate("MainWindow", "Todos los casos de carga seleccionados serán sumados. Por ejemplo, cargas permanentes.", None))
        self.radioButton_Y.setStatusTip(_translate("MainWindow", "Suma los valores de los casos de carga seleccionados.", None))
        self.radioButton_Y.setText(_translate("MainWindow", "Y (+)", None))
        self.radioButton_YO.setToolTip(_translate("MainWindow", "De los casos de carga seleccionados se extraerán los valores máximos y mínimos de entre todos o de su combinación. Por ejemplo, sobrecargas.", None))
        self.radioButton_YO.setStatusTip(_translate("MainWindow", "Valor máximo y mínimo de entre los valores de los casos de carga seleccionados o de su suma.", None))
        self.radioButton_YO.setText(_translate("MainWindow", "Y/O (¤)", None))
        self.radioButton_O.setToolTip(_translate("MainWindow", "De los casos de carga seleccionados se extraerán los valores máximos y mínimos de entre todos. Por ejemplo, viento y sismo.", None))
        self.radioButton_O.setStatusTip(_translate("MainWindow", "Valor máximo y mínimo de entre los valores de los casos de carga seleccionados.", None))
        self.radioButton_O.setText(_translate("MainWindow", "O (o)", None))
        self.pushButton_selecciona_cc.setStatusTip(_translate("MainWindow", "Selecciona los casos de carga para las implantaciones.", None))
        self.pushButton_selecciona_cc.setText(_translate("MainWindow", ">", None))
        self.pushButton_selecciona_todos_cc.setStatusTip(_translate("MainWindow", "Selecciona todos los casos de carga para las implantaciones.", None))
        self.pushButton_selecciona_todos_cc.setText(_translate("MainWindow", ">>", None))
        self.pushButton_deselecciona_cc.setStatusTip(_translate("MainWindow", "Elimina de la selección los casos de carga para las implantaciones.", None))
        self.pushButton_deselecciona_cc.setText(_translate("MainWindow", "<", None))
        self.pushButton_deselecciona_todos_cc.setStatusTip(_translate("MainWindow", "Elimina de la selección todos los grupos de casos de carga para las implantaciones.", None))
        self.pushButton_deselecciona_todos_cc.setText(_translate("MainWindow", "<<", None))
        self.label_casos_carga_grupo.setText(_translate("MainWindow", "Casos de carga en grupo:", None))
        self.listWidget_casos_carga_grupo.setStatusTip(_translate("MainWindow", "Lista con los casos de carga en el grupo.", None))
        self.pushButton_deselecciona_grp.setStatusTip(_translate("MainWindow", "Elimina de la selección los grupos de casos de carga para las implantaciones.", None))
        self.pushButton_deselecciona_grp.setText(_translate("MainWindow", "< <", None))
        self.pushButton_deselecciona_todos_grp.setStatusTip(_translate("MainWindow", "Elimina de la selección todos los casos de carga para las implantaciones.", None))
        self.pushButton_deselecciona_todos_grp.setText(_translate("MainWindow", "<< <<", None))
        self.label_grupos_casos_carga.setText(_translate("MainWindow", "Grupos de casos de carga:", None))
        self.listWidget_grupos_casos_carga.setToolTip(_translate("MainWindow", "Arrastrar grupos para ordenar.", None))
        self.listWidget_grupos_casos_carga.setStatusTip(_translate("MainWindow", "Grupos de casos de carga.", None))
        self.tabWidget_hades.setTabText(self.tabWidget_hades.indexOf(self.tab_2), _translate("MainWindow", "Casos de carga", None))
        self.label_nudos_apoyo.setText(_translate("MainWindow", "Nudos con apoyo en archivos csv:", None))
        self.listWidget_nudos_apoyo.setStatusTip(_translate("MainWindow", "Lista con los nudos en los modelos de Robot.", None))
        self.pushButton_nudos.setStatusTip(_translate("MainWindow", "Selecciona el(los) nudo(s) para el apoyo.", None))
        self.pushButton_nudos.setText(_translate("MainWindow", "> Seleccionar nudo(s)", None))
        self.pushButton_deseleccionar_nudos.setText(_translate("MainWindow", "< Deseleccionar nudo(s)", None))
        self.label_nudos.setText(_translate("MainWindow", "Nudo(s) seleccionado(s):", None))
        self.lineEdit_nudos.setStatusTip(_translate("MainWindow", "Nudo(s) seleccionado(s) para el apoyo.", None))
        self.label_apoyo.setText(_translate("MainWindow", "Nombre del apoyo:", None))
        self.lineEdit_apoyo.setStatusTip(_translate("MainWindow", "Nombre del apoyo para cuadro de implantación.", None))
        self.pushButton_apoyo.setStatusTip(_translate("MainWindow", "Crea apoyo para el cuadro de implantación.", None))
        self.pushButton_apoyo.setText(_translate("MainWindow", "Crear apoyo >", None))
        self.pushButton_deselecciona_apy.setStatusTip(_translate("MainWindow", "Elimina de la selección los apoyos para el cuadro de implantación.", None))
        self.pushButton_deselecciona_apy.setText(_translate("MainWindow", "<", None))
        self.pushButton_deselecciona_todos_apy.setStatusTip(_translate("MainWindow", "Elimina de la selección todos los apoyos para el cuadro de implantación.", None))
        self.pushButton_deselecciona_todos_apy.setText(_translate("MainWindow", "<<", None))
        self.label_apoyos_implantacion.setText(_translate("MainWindow", "Apoyos para cuadro de implantación:", None))
        self.listWidget_apoyos_implantacion.setStatusTip(_translate("MainWindow", "Lista con los apoyos para el cuadro de implantación.", None))
        self.tabWidget_hades.setTabText(self.tabWidget_hades.indexOf(self.tab_3), _translate("MainWindow", "Apoyos", None))
        self.label_apoyos.setText(_translate("MainWindow", "Apoyos:", None))
        self.listWidget_apoyos.setStatusTip(_translate("MainWindow", "Lista con los apoyos para implantación.", None))
        self.pushButton_apoyos.setStatusTip(_translate("MainWindow", "Selecciona el(los) apoyo(s) para asignar el nº de puntos.", None))
        self.pushButton_apoyos.setText(_translate("MainWindow", "> Seleccionar apoyo(s)", None))
        self.pushButton_deseleccionar_apoyos.setText(_translate("MainWindow", "< Deseleccionar apoyo(s)", None))
        self.label_apoyos_seleccionados.setText(_translate("MainWindow", "Apoyo(s) seleccionado(s):", None))
        self.lineEdit_apoyos_seleccionados.setStatusTip(_translate("MainWindow", "Apoyo(s) seleccionado(s) para asignar el nº de puntos.", None))
        self.label_n_puntos_apoyo.setText(_translate("MainWindow", "Nº de puntos por apoyo:", None))
        self.lineEdit_puntos_apoyo.setStatusTip(_translate("MainWindow", "Nº de puntos a asignar al(os) apoyo(s).", None))
        self.pushButton_puntos.setStatusTip(_translate("MainWindow", "Asigna el nº de puntos al(os) apoyo(s) para el cuadro de implantación.", None))
        self.pushButton_puntos.setText(_translate("MainWindow", "Asignar puntos por apoyo >", None))
        self.pushButton_deselecciona_pto.setStatusTip(_translate("MainWindow", "Elimina de la selección el nº de puntos por apoyo para el cuadro de implantación.", None))
        self.pushButton_deselecciona_pto.setText(_translate("MainWindow", "<", None))
        self.pushButton_deselecciona_todos_pto.setStatusTip(_translate("MainWindow", "Elimina de la selección todos los nº de puntos por apoyo para el cuadro de implantación.", None))
        self.pushButton_deselecciona_todos_pto.setText(_translate("MainWindow", "<<", None))
        self.label_puntos_apoyo.setText(_translate("MainWindow", "Puntos por apoyo:", None))
        self.listWidget_puntos_apoyo.setStatusTip(_translate("MainWindow", "Lista con los apoyos para el cuadro de implantación.", None))
        self.tabWidget_hades.setTabText(self.tabWidget_hades.indexOf(self.tab_7), _translate("MainWindow", "Nº de puntos", None))
        self.pushButton_reacciones_rsa.setStatusTip(_translate("MainWindow", "Muestra las reacciones de Robot.", None))
        self.pushButton_reacciones_rsa.setText(_translate("MainWindow", "Reacciones RSA", None))
        self.pushButton_reacciones_implantacion.setStatusTip(_translate("MainWindow", "Muestra las reacciones de la implantación.", None))
        self.pushButton_reacciones_implantacion.setText(_translate("MainWindow", "Reacciones Implantación", None))
        self.groupBox_coeficiente_implantacion.setTitle(_translate("MainWindow", "Coeficientes de implantación", None))
        self.comboBox_coeficiente_implantacion.setStatusTip(_translate("MainWindow", "Coeficiente de implantación.", None))
        self.label_coeficiente_implantacion.setText(_translate("MainWindow", "Coeficiente de implantación:", None))
        self.label_grupos_implantacion.setText(_translate("MainWindow", "Grupos para cuadro de implantación:", None))
        self.listWidget_grupos_implantacion.setStatusTip(_translate("MainWindow", "Grupos para el cuadro de implantación.", None))
        self.label_coeficientes_implantacion.setText(_translate("MainWindow", "Coeficientes para cuadro de implantación:", None))
        self.listWidget_coeficientes_implantacion.setToolTip(_translate("MainWindow", "<html><head/><body><p>En el cuadro de implantación los grupos de cargas aparecerán con el orden mostrado en esta lista.</p><p>Para modificar el orden presionar sobre el grupo de cargas y arrastrar a la posición deseada.</p></body></html>", None))
        self.listWidget_coeficientes_implantacion.setStatusTip(_translate("MainWindow", "Coeficientes para el cuadro de implantación.", None))
        self.pushButton_selecciona_grp_coef.setStatusTip(_translate("MainWindow", "Aplica el coeficiente al(os) grupo(s) seleccionado(s).", None))
        self.pushButton_selecciona_grp_coef.setText(_translate("MainWindow", ">", None))
        self.pushButton_selecciona_todos_grp_coef.setStatusTip(_translate("MainWindow", "Aplica el coeficiente a todos los grupos.", None))
        self.pushButton_selecciona_todos_grp_coef.setText(_translate("MainWindow", ">>", None))
        self.pushButton_deselecciona_grp_coef.setStatusTip(_translate("MainWindow", "Elimina el coeficiente de (los) grupo(s) seleccionado(s).", None))
        self.pushButton_deselecciona_grp_coef.setText(_translate("MainWindow", "<", None))
        self.pushButton_deselecciona_todos_grp_coef.setStatusTip(_translate("MainWindow", "Elimina todos los coeficientes de todos los grupos.", None))
        self.pushButton_deselecciona_todos_grp_coef.setText(_translate("MainWindow", "<<", None))
        self.pushButton_cuadro_implantacion.setStatusTip(_translate("MainWindow", "Vuelca los resultados a una tabla Excel.", None))
        self.pushButton_cuadro_implantacion.setText(_translate("MainWindow", "Cuadro de Implantación", None))
        self.tabWidget_hades.setTabText(self.tabWidget_hades.indexOf(self.tab_4), _translate("MainWindow", "Implantaciones", None))
        self.tabWidget_hades.setTabText(self.tabWidget_hades.indexOf(self.tab_6), _translate("MainWindow", "Page", None))
        self.tabWidget_hades.setTabText(self.tabWidget_hades.indexOf(self.tab_5), _translate("MainWindow", "Page", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.menuProyecto.setTitle(_translate("MainWindow", "Proyecto", None))
        self.menuImplantaci_n.setTitle(_translate("MainWindow", "Implantación", None))
        self.actionDatos_de_proyecto.setText(_translate("MainWindow", "Datos de proyecto", None))
        self.actionPropiedades.setText(_translate("MainWindow", "Propiedades", None))

