# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_0_0.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(660, 692)
        MainWindow.setStyleSheet(_fromUtf8("/*\n"
"QTableWidget{\n"
"    setColumnWidth(0, 70);\n"
"    setColumnWidth(1, 40);\n"
"    setColumnWidth(2, 20);\n"
"    setColumnWidth(3, 10);\n"
"    setColumnWidth(4, 20);\n"
"    setColumnWidth(5, 10);\n"
"    setColumnWidth(6, 20);\n"
"}\n"
"*/\n"
"\n"
"\n"
"QTableWidget{\n"
"    verticalHeader(1).width(5)\n"
"}"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_Poseidon = QtGui.QLabel(self.centralwidget)
        self.label_Poseidon.setGeometry(QtCore.QRect(20, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.label_Poseidon.setFont(font)
        self.label_Poseidon.setObjectName(_fromUtf8("label_Poseidon"))
        self.groupBox_Entrada = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_Entrada.setGeometry(QtCore.QRect(20, 140, 621, 201))
        self.groupBox_Entrada.setObjectName(_fromUtf8("groupBox_Entrada"))
        self.checkBox_EjeX = QtGui.QCheckBox(self.groupBox_Entrada)
        self.checkBox_EjeX.setGeometry(QtCore.QRect(20, 30, 121, 17))
        self.checkBox_EjeX.setChecked(True)
        self.checkBox_EjeX.setObjectName(_fromUtf8("checkBox_EjeX"))
        self.checkBox_EjeY = QtGui.QCheckBox(self.groupBox_Entrada)
        self.checkBox_EjeY.setGeometry(QtCore.QRect(20, 60, 121, 17))
        self.checkBox_EjeY.setObjectName(_fromUtf8("checkBox_EjeY"))
        self.checkBox_EjeZ = QtGui.QCheckBox(self.groupBox_Entrada)
        self.checkBox_EjeZ.setGeometry(QtCore.QRect(20, 90, 121, 17))
        self.checkBox_EjeZ.setObjectName(_fromUtf8("checkBox_EjeZ"))
        self.label_agRx = QtGui.QLabel(self.groupBox_Entrada)
        self.label_agRx.setGeometry(QtCore.QRect(160, 30, 46, 13))
        self.label_agRx.setObjectName(_fromUtf8("label_agRx"))
        self.lineEdit_agRx = QtGui.QLineEdit(self.groupBox_Entrada)
        self.lineEdit_agRx.setGeometry(QtCore.QRect(210, 30, 113, 20))
        self.lineEdit_agRx.setObjectName(_fromUtf8("lineEdit_agRx"))
        self.lineEdit_agRy = QtGui.QLineEdit(self.groupBox_Entrada)
        self.lineEdit_agRy.setGeometry(QtCore.QRect(210, 60, 113, 20))
        self.lineEdit_agRy.setObjectName(_fromUtf8("lineEdit_agRy"))
        self.label_agRy = QtGui.QLabel(self.groupBox_Entrada)
        self.label_agRy.setGeometry(QtCore.QRect(160, 60, 46, 13))
        self.label_agRy.setObjectName(_fromUtf8("label_agRy"))
        self.lineEdit_agRz = QtGui.QLineEdit(self.groupBox_Entrada)
        self.lineEdit_agRz.setGeometry(QtCore.QRect(210, 90, 113, 20))
        self.lineEdit_agRz.setObjectName(_fromUtf8("lineEdit_agRz"))
        self.label_agRz = QtGui.QLabel(self.groupBox_Entrada)
        self.label_agRz.setGeometry(QtCore.QRect(160, 90, 46, 13))
        self.label_agRz.setObjectName(_fromUtf8("label_agRz"))
        self.lineEdit_Beta = QtGui.QLineEdit(self.groupBox_Entrada)
        self.lineEdit_Beta.setGeometry(QtCore.QRect(460, 120, 113, 20))
        self.lineEdit_Beta.setObjectName(_fromUtf8("lineEdit_Beta"))
        self.lineEdit_q = QtGui.QLineEdit(self.groupBox_Entrada)
        self.lineEdit_q.setGeometry(QtCore.QRect(460, 90, 113, 20))
        self.lineEdit_q.setObjectName(_fromUtf8("lineEdit_q"))
        self.label_Beta = QtGui.QLabel(self.groupBox_Entrada)
        self.label_Beta.setGeometry(QtCore.QRect(370, 120, 46, 13))
        self.label_Beta.setObjectName(_fromUtf8("label_Beta"))
        self.label_GammaI = QtGui.QLabel(self.groupBox_Entrada)
        self.label_GammaI.setGeometry(QtCore.QRect(370, 30, 46, 13))
        self.label_GammaI.setObjectName(_fromUtf8("label_GammaI"))
        self.comboBox_TipoTerreno = QtGui.QComboBox(self.groupBox_Entrada)
        self.comboBox_TipoTerreno.setGeometry(QtCore.QRect(120, 130, 69, 22))
        self.comboBox_TipoTerreno.setObjectName(_fromUtf8("comboBox_TipoTerreno"))
        self.comboBox_TipoTerreno.addItem(_fromUtf8(""))
        self.comboBox_TipoTerreno.addItem(_fromUtf8(""))
        self.comboBox_TipoTerreno.addItem(_fromUtf8(""))
        self.comboBox_TipoTerreno.addItem(_fromUtf8(""))
        self.comboBox_TipoTerreno.addItem(_fromUtf8(""))
        self.label_q = QtGui.QLabel(self.groupBox_Entrada)
        self.label_q.setGeometry(QtCore.QRect(370, 90, 101, 16))
        self.label_q.setObjectName(_fromUtf8("label_q"))
        self.lineEdit_GammaI = QtGui.QLineEdit(self.groupBox_Entrada)
        self.lineEdit_GammaI.setGeometry(QtCore.QRect(460, 30, 113, 20))
        self.lineEdit_GammaI.setObjectName(_fromUtf8("lineEdit_GammaI"))
        self.label_TipoTerreno = QtGui.QLabel(self.groupBox_Entrada)
        self.label_TipoTerreno.setGeometry(QtCore.QRect(30, 130, 91, 16))
        self.label_TipoTerreno.setObjectName(_fromUtf8("label_TipoTerreno"))
        self.label_TipoEspectro = QtGui.QLabel(self.groupBox_Entrada)
        self.label_TipoEspectro.setGeometry(QtCore.QRect(30, 160, 101, 16))
        self.label_TipoEspectro.setObjectName(_fromUtf8("label_TipoEspectro"))
        self.comboBox_TipoEspectro = QtGui.QComboBox(self.groupBox_Entrada)
        self.comboBox_TipoEspectro.setGeometry(QtCore.QRect(120, 160, 69, 22))
        self.comboBox_TipoEspectro.setObjectName(_fromUtf8("comboBox_TipoEspectro"))
        self.comboBox_TipoEspectro.addItem(_fromUtf8(""))
        self.comboBox_TipoEspectro.addItem(_fromUtf8(""))
        self.lineEdit_Mi = QtGui.QLineEdit(self.groupBox_Entrada)
        self.lineEdit_Mi.setGeometry(QtCore.QRect(460, 60, 113, 20))
        self.lineEdit_Mi.setObjectName(_fromUtf8("lineEdit_Mi"))
        self.label_Mi = QtGui.QLabel(self.groupBox_Entrada)
        self.label_Mi.setGeometry(QtCore.QRect(370, 60, 101, 16))
        self.label_Mi.setObjectName(_fromUtf8("label_Mi"))
        self.groupBox_Salida = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_Salida.setGeometry(QtCore.QRect(20, 350, 621, 281))
        self.groupBox_Salida.setObjectName(_fromUtf8("groupBox_Salida"))
        self.pushButton_ag_T = QtGui.QPushButton(self.groupBox_Salida)
        self.pushButton_ag_T.setGeometry(QtCore.QRect(20, 30, 271, 23))
        self.pushButton_ag_T.setObjectName(_fromUtf8("pushButton_ag_T"))
        self.label = QtGui.QLabel(self.groupBox_Salida)
        self.label.setGeometry(QtCore.QRect(20, 120, 551, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.tableWidget_Parametros = QtGui.QTableWidget(self.groupBox_Salida)
        self.tableWidget_Parametros.setGeometry(QtCore.QRect(20, 150, 581, 115))
        self.tableWidget_Parametros.setMinimumSize(QtCore.QSize(581, 0))
        self.tableWidget_Parametros.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_Parametros.setStyleSheet(_fromUtf8(""))
        self.tableWidget_Parametros.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_Parametros.setAutoScroll(True)
        self.tableWidget_Parametros.setShowGrid(True)
        self.tableWidget_Parametros.setWordWrap(True)
        self.tableWidget_Parametros.setCornerButtonEnabled(True)
        self.tableWidget_Parametros.setRowCount(3)
        self.tableWidget_Parametros.setObjectName(_fromUtf8("tableWidget_Parametros"))
        self.tableWidget_Parametros.setColumnCount(8)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Parametros.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Parametros.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Parametros.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Parametros.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Parametros.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Parametros.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Parametros.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_Parametros.setHorizontalHeaderItem(7, item)
        self.tableWidget_Parametros.horizontalHeader().setVisible(True)
        self.tableWidget_Parametros.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidget_Parametros.horizontalHeader().setHighlightSections(True)
        self.tableWidget_Parametros.horizontalHeader().setMinimumSectionSize(35)
        self.tableWidget_Parametros.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget_Parametros.horizontalHeader().setStretchLastSection(False)
        self.tableWidget_Parametros.verticalHeader().setVisible(False)
        self.tableWidget_Parametros.verticalHeader().setDefaultSectionSize(30)
        self.pushButton_respuesta_elastica = QtGui.QPushButton(self.groupBox_Salida)
        self.pushButton_respuesta_elastica.setGeometry(QtCore.QRect(20, 60, 271, 23))
        self.pushButton_respuesta_elastica.setObjectName(_fromUtf8("pushButton_respuesta_elastica"))
        self.pushButton_analisis_elastico = QtGui.QPushButton(self.groupBox_Salida)
        self.pushButton_analisis_elastico.setGeometry(QtCore.QRect(20, 90, 271, 23))
        self.pushButton_analisis_elastico.setObjectName(_fromUtf8("pushButton_analisis_elastico"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 311, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 351, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 110, 581, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 660, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuArchivo = QtGui.QMenu(self.menubar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuProyecto = QtGui.QMenu(self.menubar)
        self.menuProyecto.setObjectName(_fromUtf8("menuProyecto"))
        self.menuC_lculo = QtGui.QMenu(self.menubar)
        self.menuC_lculo.setObjectName(_fromUtf8("menuC_lculo"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menuConfiguraci_n = QtGui.QMenu(self.menubar)
        self.menuConfiguraci_n.setObjectName(_fromUtf8("menuConfiguraci_n"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_ag_T = QtGui.QAction(MainWindow)
        self.action_ag_T.setObjectName(_fromUtf8("action_ag_T"))
        self.menuC_lculo.addAction(self.action_ag_T)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuProyecto.menuAction())
        self.menubar.addAction(self.menuC_lculo.menuAction())
        self.menubar.addAction(self.menuConfiguraci_n.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_Poseidon.setText(_translate("MainWindow", "Poseidon", None))
        self.groupBox_Entrada.setTitle(_translate("MainWindow", "Datos de entrada", None))
        self.checkBox_EjeX.setStatusTip(_translate("MainWindow", "Acción sísmica en el eje x o longitudinal.", None))
        self.checkBox_EjeX.setText(_translate("MainWindow", "Eje x - longitudinal", None))
        self.checkBox_EjeY.setStatusTip(_translate("MainWindow", "Acción sísmica en el eje y o transversal.", None))
        self.checkBox_EjeY.setText(_translate("MainWindow", "Eje y - transversal", None))
        self.checkBox_EjeZ.setStatusTip(_translate("MainWindow", "Acción sísmica en el eje z o vertical.", None))
        self.checkBox_EjeZ.setText(_translate("MainWindow", "Eje z - vertical", None))
        self.label_agRx.setStatusTip(_translate("MainWindow", "Aceleración máxima de referencia del suelo en un terrano tipo A en la dirección x.", None))
        self.label_agRx.setText(_translate("MainWindow", "a.gR", None))
        self.lineEdit_agRx.setStatusTip(_translate("MainWindow", "Aceleración máxima de referencia del suelo en un terreno tipo A en la dirección x.", None))
        self.lineEdit_agRy.setStatusTip(_translate("MainWindow", "Aceleración máxima de referencia del suelo en un terreno tipo A en la dirección y.", None))
        self.label_agRy.setStatusTip(_translate("MainWindow", "Aceleración máxima de referencia del suelo en un terrano tipo A en la dirección y.", None))
        self.label_agRy.setText(_translate("MainWindow", "a.gR", None))
        self.lineEdit_agRz.setStatusTip(_translate("MainWindow", "Aceleración máxima de referencia del suelo en un terreno tipo A en la dirección z.", None))
        self.label_agRz.setStatusTip(_translate("MainWindow", "Aceleración máxima de referencia del suelo en un terrano tipo A en la dirección z.", None))
        self.label_agRz.setText(_translate("MainWindow", "a.gR", None))
        self.lineEdit_Beta.setToolTip(_translate("MainWindow", "El valor recomendado es 0,2.", None))
        self.lineEdit_Beta.setStatusTip(_translate("MainWindow", "Coeficiente correspondiente al umbral inferior del espectro de cálculo horizontal (3.2.2.5 (4)P).", None))
        self.lineEdit_Beta.setText(_translate("MainWindow", "0.2", None))
        self.lineEdit_q.setToolTip(_translate("MainWindow", "Ver tablas 6.1, 6.2, 6.3; apartados 6.5 a 6.11 y especialmente 4.4.1 (2).", None))
        self.lineEdit_q.setStatusTip(_translate("MainWindow", "Coeficiente de comportamiento (6.1, 6.2, 6.3, 6.5, 6.11, 4.4.1 (2)).", None))
        self.label_Beta.setStatusTip(_translate("MainWindow", "Coeficiente correspondiente al umbral inferior del espectro de cálculo horizontal (3.2.2.5 (4)P).", None))
        self.label_Beta.setText(_translate("MainWindow", "b", None))
        self.label_GammaI.setStatusTip(_translate("MainWindow", "Coeficiente de importancia (3.2.1 (3)).", None))
        self.label_GammaI.setText(_translate("MainWindow", "g.I", None))
        self.comboBox_TipoTerreno.setStatusTip(_translate("MainWindow", "Tipo de terreno (3.1.2).", None))
        self.comboBox_TipoTerreno.setItemText(0, _translate("MainWindow", "A", None))
        self.comboBox_TipoTerreno.setItemText(1, _translate("MainWindow", "B", None))
        self.comboBox_TipoTerreno.setItemText(2, _translate("MainWindow", "C", None))
        self.comboBox_TipoTerreno.setItemText(3, _translate("MainWindow", "D", None))
        self.comboBox_TipoTerreno.setItemText(4, _translate("MainWindow", "E", None))
        self.label_q.setStatusTip(_translate("MainWindow", "Coeficiente de comportamiento (6.1, 6.2, 6.3, 6.5, 6.11, 4.4.1 (2)).", None))
        self.label_q.setText(_translate("MainWindow", "q", None))
        self.lineEdit_GammaI.setStatusTip(_translate("MainWindow", "Coeficiente de importancia (3.2.1 (3)).", None))
        self.label_TipoTerreno.setStatusTip(_translate("MainWindow", "Tipo de terreno (3.1.2).", None))
        self.label_TipoTerreno.setText(_translate("MainWindow", "Tipo de terreno", None))
        self.label_TipoEspectro.setStatusTip(_translate("MainWindow", "Tipo de espectro 3.2.2.2 (2)P.", None))
        self.label_TipoEspectro.setText(_translate("MainWindow", "Tipo de espectro", None))
        self.comboBox_TipoEspectro.setStatusTip(_translate("MainWindow", "Tipo de espectro 3.2.2.2 (2)P.", None))
        self.comboBox_TipoEspectro.setItemText(0, _translate("MainWindow", "1", None))
        self.comboBox_TipoEspectro.setItemText(1, _translate("MainWindow", "2", None))
        self.lineEdit_Mi.setToolTip(_translate("MainWindow", "= 1 para un amortiguamiento viscoso del 5 %.", None))
        self.lineEdit_Mi.setStatusTip(_translate("MainWindow", "Coeficiente de corrección del amortiguamiento (3.2.2.2 (1)P).", None))
        self.label_Mi.setStatusTip(_translate("MainWindow", "Coeficiente de corrección del amortiguamiento (3.2.2.2 (1)P).", None))
        self.label_Mi.setText(_translate("MainWindow", "mi", None))
        self.groupBox_Salida.setTitle(_translate("MainWindow", "Datos de salida", None))
        self.pushButton_ag_T.setStatusTip(_translate("MainWindow", "Calcula las aceleraciones y periodos.", None))
        self.pushButton_ag_T.setText(_translate("MainWindow", "Aceleraciones y periodos", None))
        self.label.setText(_translate("MainWindow", "Valores de los parámetros que describen el espectro de respuesta elástica recomendados:", None))
        item = self.tableWidget_Parametros.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Espectro", None))
        item = self.tableWidget_Parametros.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tipo", None))
        item = self.tableWidget_Parametros.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Terreno", None))
        item = self.tableWidget_Parametros.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "a.g", None))
        item = self.tableWidget_Parametros.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "S", None))
        item = self.tableWidget_Parametros.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "T.B (s)", None))
        item = self.tableWidget_Parametros.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "T.C (s)", None))
        item = self.tableWidget_Parametros.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "T.D (s)", None))
        self.pushButton_respuesta_elastica.setStatusTip(_translate("MainWindow", "Forma del espectro de respuesta elástica.", None))
        self.pushButton_respuesta_elastica.setText(_translate("MainWindow", "Forma del espectro de respuesta elástica", None))
        self.pushButton_analisis_elastico.setStatusTip(_translate("MainWindow", "Forma del espectro de cálculo para el análisis elástico.", None))
        self.pushButton_analisis_elastico.setText(_translate("MainWindow", "Forma del espectro de cálculo para el análisis elástico", None))
        self.label_4.setText(_translate("MainWindow", "EN 1998-1:2004", None))
        self.label_5.setText(_translate("MainWindow", "Eurocódigo 8: Proyecto de estructuras sismorresistentes", None))
        self.label_6.setText(_translate("MainWindow", "Parte 1: Reglas generales, acciones sísmicas y reglas para la edificación", None))
        self.label_7.setText(_translate("MainWindow", "Espectro de respuesta elástica y espectro de cálculo para análisis elástico (apartados 3.2.2.2; 3.2.2.3; 3.2.2.5)", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.menuProyecto.setTitle(_translate("MainWindow", "Proyecto", None))
        self.menuC_lculo.setTitle(_translate("MainWindow", "Cálculo", None))
        self.menu.setTitle(_translate("MainWindow", "?", None))
        self.menuConfiguraci_n.setTitle(_translate("MainWindow", "Configuración", None))
        self.action_ag_T.setText(_translate("MainWindow", "Aceleraciones y periodos", None))
        self.action_ag_T.setStatusTip(_translate("MainWindow", "Paso del periódo de vibración.", None))

